export enum ETypeOfBug {
  New = 'new',
  Fixed = 'fixed',
}

export enum EAnalyticsEvent {
  /**
   * button Logs
   */
  BTN = 'BTN',
  REGISTER_PARTNER = 'REGISTER_PARTNER',
  ADD_TO_CART = 'ADD_TO_CART',
  BUY_NOW = 'BUY_NOW',
  SUBMIT_CREATE_ORDER = 'SUBMIT_CREATE_ORDER',
  REBUY = 'REBUY',
  ORDER_SUPPORT = 'ORDER_SUPPORT',
  SHOW_REVIEW = 'SHOW_REVIEW',
  CREATE_REVIEW = 'CREATE_REVIEW',
  SUBMIT_REVIEW = 'SUBMIT_REVIEW',
  SHOW_PRODUCT = 'SHOW_PRODUCT',
  BANNER_POPUP = 'BANNER_POPUP',
  BANNER_BIG = 'BANNER_BIG',
  BANNER_SMALL = 'BANNER_SMALL',
  LIKE_PRODUCT = 'LIKE_PRODUCT',
  CATEGORY = 'CATEGORY',
  BRAND = 'BRAND',
  VIDEO_REVIEW = 'VIDEO_REVIEW',
  DAILY_GIFT = 'DAILY_GIFT',
  LUCKY_WHEEL = 'LUCKY_WHEEL',
  WITHDRAW = 'WITHDRAW',
  SUBMIT_WITHDRAW = 'SUBMIT_WITHDRAW',
  SUBMIT_REGISTER_PARTNER = 'SUBMIT_REGISTER_PARTNER',
  SUBMIT_REGISTER_COLLABORATOR = 'SUBMIT_REGISTER_COLLABORATOR',
  REGISTER_PARTNER_FEE = 'SUBMIT_REGISTER_PARTNER_FEE',
  SHARE_BUY = 'SHARE_BUY',
  SUBMIT_SHARE_POST = 'SUBMIT_SHARE_POST',
  SUBMIT_SHARE_BUY = 'SUBMIT_SHARE_BUY',
  COPY_SHARE_BUY = 'COPY_SHARE_BUY',
  DOWNLOAD_SHARE_BUY = 'DOWNLOAD_SHARE_BUY',
  GEN_SHARE_BUY = 'GEN_SHARE_BUY',
  GEN_POST = 'GEN_POST',
}
