/**
 * List of screen's name
 */
export const NAVIGATION_LOGIN_SCREEN = 'NAVIGATION_LOGIN_SCREEN'


//Main navigation
export const NAVIGATION_MAIN_NAVIGATION = 'NAVIGATION_MAIN_NAVIGATION'
export const NAVIGATION_HOME_SCREEN = 'NAVIGATION_HOME_SCREEN'
export const NAVIGATION_LOGS_BUG_SCREEN = 'NAVIGATION_LOGS_BUG_SCREEN'
export const NAVIGATION_DETAIL_LOGS_BUG_SCREEN = 'NAVIGATION_DETAIL_LOGS_BUG_SCREEN'
export const NAVIGATION_RELEASE_LOGS_SCREEN = 'NAVIGATION_RELEASE_LOGS_SCREEN'
